### ISSUE TITLE
Using ESP8266 for transmitter as well

### ISSUE THREAD

**Issue by bleightyturner** [hennedo/wifitally#1]
I know you mentioned the atem needing a stable connection. Was just curious if you’d tried using a ESP8266 for the sender as well and whether that didn’t work as well. Thanks.

**Comment by hennedo** [comment]
Hey! Sorry for the late reply. 
Until now I didn't test the esp8266 as transmitter. But since I got new accesspoints, at least the ATEM software on my mac seems to be working stable via WiFi. I got an unused ESP32 board here and will try that. 

But keep in mind, even if it works with my accesspoints, that doesn't mean it's working with every wireless access point.

**Comment by bleightyturner** [comment]
Makes sense. Thanks
